# Generated by Django 3.2.9 on 2021-11-06 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CropInsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parappu_list', models.TextField(max_length=30)),
                ('acre_amount', models.CharField(max_length=30)),
                ('total_cent', models.CharField(max_length=30)),
                ('total_acre', models.CharField(max_length=30)),
                ('total_amount', models.CharField(max_length=30)),
                ('round_amount', models.CharField(max_length=30)),
                ('total_parappu', models.CharField(max_length=30)),
            ],
        ),
    ]
